package uk.pcn.invoice.common;

public enum RateCardXML {
	BRIGADE_CLOTHING_YODEL, EMOTIVE_LTD_YODEL, JADE_ENGINEERING_LTD_YODEL, MANOR_HYGIENE_YODEL,
	SPHINX_IND_SUPPLIERS_YODEL, THERMOSCREEENS_LTD_YODEL, VEHICLE_SHIFT_AND_STORE_LTD_YODEL;
}
